### PR TITLE
Adds support for SVG's `width` and `height` options.

### PR DESCRIPTION
**Pull request by jumarko**
These are supported by async profiler as documented here: https://github.com/jvm-profiling-tools/async-profiler#profiler-options
Source code as a useful reference: https://github.com/jvm-profiling-tools/async-profiler/blob/e167d53755c7a3e85db22042c636418966e03d53/src/arguments.h#L126

### CODE REVIEW

**Comment by jumarko** [comment]
@alexander-yakushev is this acceptable or does it need some tuning?

**Comment by jumarko** [comment]
@alexander-yakushev Any updated on this? It would be really nice to have it merged - if it needs some cleanup, please let me know.

**Comment by alexander-yakushev** [comment]
Sorry, completely forgot about it! Thank you, this is surely useful.

**Comment by alexander-yakushev** [comment]
Pushed as 0.3.2-SNAPSHOT.

**Pull request merged**
